"""add replied status

Revision ID: 16c06fcee55c
Revises: 8203fd973acf
Create Date: 2026-01-15 15:31:14.345346

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16c06fcee55c"
down_revision: Union[str, Sequence[str], None] = "8203fd973acf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE campaigndeliverystatus ADD VALUE IF NOT EXISTS 'REPLIED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
