"""add reply_count

Revision ID: 17f50817a426
Revises: e3412477ff4d
Create Date: 2026-01-15 13:21:38.309659

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17f50817a426"
down_revision: Union[str, Sequence[str], None] = "e3412477ff4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaigns",
        sa.Column("replied_count", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "replied_count")
    # ### end Alembic commands ###
