"""remove_default_language_from_quick_replies

Revision ID: 42b891ba34f0
Revises: f1cbf7dab897
Create Date: 2026-01-24 20:02:53.089762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b891ba34f0'
down_revision: Union[str, Sequence[str], None] = 'f1cbf7dab897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quick_replies', 'default_language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quick_replies', sa.Column('default_language', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
