"""add reaction and reply_to_message_id

Revision ID: 61c1c8f18990
Revises: e2ba5f2e4099
Create Date: 2026-01-05 20:57:15.197085

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c1c8f18990'
down_revision: Union[str, Sequence[str], None] = 'e2ba5f2e4099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_message_id', sa.Uuid(), nullable=True))
    op.add_column('messages', sa.Column('reaction', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'reaction')
    op.drop_column('messages', 'reply_to_message_id')
    # ### end Alembic commands ###
