"""add is_replied

Revision ID: 751179ae6f8e
Revises: 17f50817a426
Create Date: 2026-01-15 13:40:33.441880

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "751179ae6f8e"
down_revision: Union[str, Sequence[str], None] = "17f50817a426"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaign_contacts",
        sa.Column("is_replied", sa.Boolean(), nullable=False, server_default="False"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaign_contacts", "is_replied")
    # ### end Alembic commands ###
