"""fix_error_code_type

Revision ID: b53d1dd3156a
Revises: e7d8e399fd23
Create Date: 2026-01-23 17:00:12.221870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b53d1dd3156a'
down_revision: Union[str, Sequence[str], None] = 'e7d8e399fd23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_contacts', 'error_message')
    op.add_column('messages', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('error_code', sa.Integer(), nullable=True))
    op.alter_column('templates', 'default_variable_mapping',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templates', 'default_variable_mapping',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('messages', 'error_code')
    op.drop_column('messages', 'error_message')
    op.add_column('campaign_contacts', sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
