"""add soft delete to template

Revision ID: b8d2b3a79b28
Revises: f79c8da494da
Create Date: 2026-01-22 13:15:54.200294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d2b3a79b28'
down_revision: Union[str, Sequence[str], None] = 'f79c8da494da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'waba_phone_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.add_column('templates', sa.Column('is_deleted', sa.Boolean(),
                  nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_templates_is_deleted'),
                    'templates', ['is_deleted'], unique=False)
    op.add_column('waba_phone_numbers', sa.Column(
        'is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_waba_phone_numbers_is_deleted'),
                    'waba_phone_numbers', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waba_phone_numbers_is_deleted'),
                  table_name='waba_phone_numbers')
    op.drop_column('waba_phone_numbers', 'is_deleted')
    op.drop_index(op.f('ix_templates_is_deleted'), table_name='templates')
    op.drop_column('templates', 'is_deleted')
    op.alter_column('messages', 'waba_phone_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    # ### end Alembic commands ###
