"""read_count

Revision ID: e3412477ff4d
Revises: d784e540d387
Create Date: 2026-01-15 13:07:12.442458

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3412477ff4d"
down_revision: Union[str, Sequence[str], None] = "d784e540d387"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaigns",
        sa.Column("read_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_foreign_key(
        "fk_contacts_last_message_id",
        "contacts",
        "messages",
        ["last_message_id"],
        ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_contacts_last_message_id", "contacts", type_="foreignkey")
    op.drop_column("campaigns", "read_count")
    # ### end Alembic commands ###
