"""remove shortcut

Revision ID: eb885d3e9438
Revises: 42b891ba34f0
Create Date: 2026-01-24 20:26:28.595682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb885d3e9438'
down_revision: Union[str, Sequence[str], None] = '42b891ba34f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quick_replies_shortcut'), table_name='quick_replies')
    op.drop_column('quick_replies', 'shortcut')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quick_replies', sa.Column('shortcut', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_quick_replies_shortcut'), 'quick_replies', ['shortcut'], unique=True)
    # ### end Alembic commands ###
