"""add quick_replies

Revision ID: f1cbf7dab897
Revises: 647f0c2ed439
Create Date: 2026-01-16 11:21:02.213784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cbf7dab897'
down_revision: Union[str, Sequence[str], None] = '647f0c2ed439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_replies',
    sa.Column('shortcut', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('default_language', sa.String(length=5), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quick_replies'))
    )
    op.create_index(op.f('ix_quick_replies_shortcut'), 'quick_replies', ['shortcut'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quick_replies_shortcut'), table_name='quick_replies')
    op.drop_table('quick_replies')
    # ### end Alembic commands ###
